### ISSUE TITLE
Help need with some text munging

### ISSUE THREAD

**Issue by NeilCFord** [Charlotteis/noquestionistupid#24]
I should know enough Python or Ruby (or shell commands for that matter) to do this, but I don't, hence the cry help.

I have a 500+ line CSV file that contains for bits of information per line. One is a Twitter ID in the normal form of @twitterID. I need to transform that into a fully formed link of the format:

    <a href="https://twitter.com/twitterID">@twitterID</a>

and either write it back out to the original file or to a new one, with the other data intact as well.

Whist a Python or Ruby solution would be great, to further my education, right now I'll take any solution that works.

Thanks in advance for any and all assistance.

Neil.

**Comment by nickcharlton** [comment]
Can you give an example few lines from the CSV file?

(Feel free to anonymise the data; it's much easier with an example.)

**Comment by cheesestraws** [comment]
Is the twitter handle always in the same place in the line?  Can there be multiple twitter handles in the line or will there only be one always?

**Comment by AMRoche** [comment]
What language are you in?

Just for a general approach, start with parsing the CSV in to arrays, and once you have the twitter ID's, just substring it to remove the @ and then insert it in the right places to;

```<a href="https://twitter.com/$YOURVARHERE">@$YOURVARHERE</a>``` .

That should take care of it handily :)

**Comment by adamauckland** [comment]
Hi, I don't know if it helps, but I just used http://papaparse.com/ to parse a CSV someone sent me

**Comment by cheesestraws** [comment]
Here's a first-cut perl solution that works on some plausible test data I invented.  The problem with parsing CSV is that ... there's really no standard for what CSV *is* beyond rough handwavy hopeful guidelines.  So, for example, this perl script assumes that whatever has generated the CSV file *hasn't* randomly double quoted values, though some do with very little provocation.

I've commented it quite ... verbosely, perhaps overly much, but it uses regexes and people tend to get a bit twitchy about those.  Their concrete syntax is awful, but they're not that difficult to understand once you get past that, and they're insanely useful.

http://fauxland.midworld.co.uk/~cheesey/twittercsv.pl

**Comment by NeilCFord** [comment]
Firstly, thank you everyone for your answers, they are very much appreciated.

@nickcharlton The data looks like this:

    South Australian Maritime Museum,@SAMaritimeMuseu,Australia,History
    Migration Museum,@MigrationMuseum,Australia,History
    Sydney Living Museums,@sydlivmus,Australia,"Architecture and heritage, Societies and civilisations"
    Carnamah Historical Society & Museum,@carnamah,Australia,History
    Sovereign Hill Museums Association,@GoldfieldsEd,Australia,"History, Societies and civilisations, Technology and industry, Theater"

@cheesestraws The twitter ID is always the second entry and there should only be one. And thank you for the Perl, off to look at it now.

@adamauckland Going to check that out, thanks.

Will report back on progress.

**Comment by nickcharlton** [comment]
I'd probably do something like this, in Ruby:

(The `data` section is a [heredoc][], it's just a string.)

```ruby
require 'csv'

data = <<EOD
South Australian Maritime Museum,@SAMaritimeMuseu,Australia,History
Migration Museum,@MigrationMuseum,Australia,History
Sydney Living Museums,@sydlivmus,Australia,"Architecture and heritage, Societies and civilisations"
Carnamah Historical Society & Museum,@carnamah,Australia,History
Sovereign Hill Museums Association,@GoldfieldsEd,Australia,"History, Societies and civilisations, Technology and industry, Theater"
EOD

CSV.parse(data) do |row|
  name = row[1]
  # take off the first '@' symbol by trimming the characters down
  handle = name[1..-1]
  
  # build up the output
  puts "<a href=\"https://twitter.com/#{handle}\">#{name}</a>"
end
```

If you were reading from a file, you'd be able to replace the CSV line like this:

```ruby
CSV.foreach(File.expand_path 'file_name.csv', __dir__) do |row|
  # the block contents from above
end
```

[heredoc]: http://en.wikipedia.org/wiki/Here_document

**Comment by NeilCFord** [comment]
@nickcharlton Thank you, that is really helpful. I'm going to have a play and learn some more Ruby.

**Comment by nickcharlton** [comment]
Excellent! Ask if anything isn't clear.

**Comment by NeilCFord** [comment]
Once again, thank you to everyone who replied and supplied options, it's really appreciated. Have completed the task for now, but am going to dissect all the solutions in order to be able to do something similar in the future.
